version: "3.4"

services: 
    lista_tarefas_api:
        container_name: lista_tarefas_api
        image: lista_tarefas
        environment: 
            - PORT=5000
        ports: 
            - 5000:5000
        build: 
            context: .
            dockerfile: Dockerfile